### ISSUE TITLE
jAccount 无法登录

### ISSUE THREAD

**Issue by VoidXia** [yuetsin/electsys-utility#28]
**Bug 描述**

**您的操作系统版本**
 - macOS 版本 10.14.6
 - Version v0.9.7(95)

**复现问题的步骤**

点击登录后，页面无反应，验证码刷新。无法登入jAccount。

**预期行为**
正常情况下预计应该发生的行为

**屏幕截图**
如果方便的话，能附上问题出现的屏幕截图就更棒了

**更多信息**

**Comment by yuetsin** [comment]
因应登录接口启用的 reCAPTCHA 保护，尝试用内嵌 WebView 的方式进行登录。

请尝试一下 [b97 fix](https://1drv.ms/u/s!AsDdIgB5xv08iK4v6vbJtOgS0yfZFA?e=dCt00y)

**Comment by VoidXia** [comment]
> 因应登录接口启用的 reCAPTCHA 保护，尝试用内嵌 WebView 的方式进行登录。
> 
> 请尝试一下 [b97 fix](https://1drv.ms/u/s!AsDdIgB5xv08iK4v6vbJtOgS0yfZFA?e=dCt00y)


解决了，谢谢！！
